### ISSUE TITLE
Version 3 Requests

### ISSUE THREAD

**Issue by Mottie** [Mottie/tablesorter#122]
## Tablesorter v3

I've been working with [thezoggy](https://github.com/thezoggy) on version 3 of the tablesorter
plugin and I'd like to get some feedback on what enhancements you would like to see. So far I have the
following, some of which have been added in version 2.4:
### Version 2.4 additions:
- [x] Themes option.
- [x] New themes! Thanks to thezoggy!
- [x] Improved widget layout (added remove functions to every widget).
- [x] Modified uitheme widget to allow choosing between jQuery UI or Bootstrap themes (may be modified or removed in v3).
- [x] Filter widget improvements (but no quicksearch, yet).
- [x] Filter widget works with pager plugin.
- [x] Added "refreshWidgets" method which can remove un-used widget and re-initialized current widgets.
### Version 3:
- Core
  - [ ] Build your own tablesorter (choose themes/widgets/plugins; thanks to thezoggy) - issue #100.
  - [ ] Easier to use documentation with simple examples.
  - [ ] Enable/disable method - see issue #117.
  - [x] Pull sort content from data attributes. See issue #154.
  - [ ] Reference a column by id or class name. See issue #237.
  - [x] <del>Change `tablesorter-headerSortUp` to `tablesorter-headerAsc` and `tablesorter-headerSortDown` to `tablesorter-headerDesc` - issue #173.</del>
- Widgets
  - [ ] Widget improvements
  - [x] Improved widget layout again... plan to add a widget options section to every widget.
  - [x] Faster filter widget
  - [x] Quick search ( will be added to the filter widget ) - see issue #114.
  - [ ] More optional widgets - see <del>#120 (static row)</del>,<del> #178 (filter save widget)</del>.
  - [x] Calculate footer totals; make this work with the filter widget as well - see issues #136 and #146.
  - [x] Make Filter + Sticky Headers work together - see issue #249.
  - [x] Toggle columns on/off widget.
- Parsers
  - [x] Include useful parsers - see #247 (iso8601) and  #83 (dynamic checkbox) sorting.
### Planned for future releases (no code written yet!):
- Core
  - Support rowspan/colspan within the tbody.
  - Sort across tbodies - right now each tbody sorts separately - or use the static row widget? issue #120
- Widgets
  - Move columns widget (maybe?).
